const filterCategories = require("../utils/filters");

module.exports.names = [
	"Argentina NCP_UOMA vs. Cargill",
	"Argentina NCP_CIPCE vs. Skanska",
	"Argentina NCP_Individual vs. Lafarge Holcim",
	"Argentina NCP_Recalde vs. ACCOR",
	"Argentina NCP_Maxiconsumo S.A vs. Molinos Rio De La Plata",
	"Argentina NCP_Individual vs. Telefonica de Argentina",
	"Argentina NCP_Individual vs. Arca Continental",
	"Argentina NCP_FOCO/INPADE vs. Barrick Gold",
	"Argentina NCP_FOCO/INPADE et al vs. SHELL",
	"Argentina NCP_Individual vs. Tenaris",
	"Argentina NCPP_Individual vs. TELECOM",
	"Argentina NCP_CEDHA vs. Glencore",
	"Argentina NCP_Banca Nazionale del Lavoro vs. Asociacion Bancar",
	"Argentina NCP_ACIJ vs. Ferrostaal Argentina S.A",
	"Argentina NCP_ACIJ vs. BNP PARIBAS",
	"Aus NCP_Sepik and Jubilee Australia vs. PanAust",
	"Aus NCP GLAN vs. BHP Group Ltd",
	"Aus NCP_Justicia y Reparacion vs. Mining company in Chile",
	"Aus NCP_PWYP vs. Mallee",
	"Aus NCP_SAVEducation Pty Ltd. vs. Indian software development c",
	"Aus NCP_ Parella Law vs. Australian MNE",
	"Aus NCP_RAID vs. G4S Australia_statement",
	"Aus NCP_RAID vs. G4S_appeal",
	"Aus NCP_IndustriALL vs. Ansell Limited",
	"Aus NCP_Individual vs. SERCO Group Pty Ltd",
	"Aus NCP_AWWB vs. Mercer PR",
	"Aus NCP_Friends of Earth vs. ANZ Group",
	"AusNCP_Port Hedland Community vs. BHP",
	"AusNCP_Individual vs.Deutsch Bank Australia",
	"AusNCP_Individuals vs. ElectraNet Pty Ltd",
	"Aus NCP_IUF vs. Coca Cola Amatil",
	"Aus NCP_Equitable Cambodia and IDI vs. ANZ Group",
	"Aus NCP_Individual vs. Australian Laboratory Services",
	"Austrian_NCP_Open Society Justice vs. Telekom Austria",
	"Austrian NCP_Finance and Trade Watch vs. Andritz Hydro",
	"Austrian NCP_Finance and Trade Watch vs. Andritz Hydro_final",
	"Belgium NCP_Open Secrets and CALS vs. KBC and KBL",
	"Belgium NCP_Minister of Enterprises vs. Brink",
	"Belgium NCP_Individual vs. Brussels Airlines",
	"Belgium NCP_KSBSI vs. ITUC and ACV-CSC",
	"Belgium NCP_Individual vs. Banro",
	"Belgium NCP_Green Peace vs. Dredging International",
	"Belgium NCP_BWI vs. Etex Group",
	"Belgium NCP_NGOs vs. Socapalm and Socfin",
	"Belgium NCP_ADIMED vs. ES-KO and Groupe KILU_initial",
	"Belgium NCP_IUF vs. AB-InBev",
	"Belgium NCP_Green Peace vs. Jan De Nul NV",
	"Brazil NCP_Industries of ABCD vs. Mappel Packaging",
	"Brazil NCP_STP vs. German MNE",
	"Brazil NCP_STIPEMA vs. General Motors",
	"Brazil NCP_CUT vs. Unilever",
	"Brazil NCP_Workers Union vs. Itau-Unibanco",
	"Brazil NCP_Individual vs. Petrobras S.A",
	"Brazil NCP_Association of Neighborhoods vs. Kinross Gold",
	"Brazil NCP_Individuals vs. VALE S.A",
	"Brazil NCP_Individual vs. VALE S.A",
	"Brazil NCP_Individuals vs. Bracell Bahia Specialty Cellulose S.",
	"Brazil NCP_German Parlamentarian vs. C&A Modas",
	"Brazil NCP_Group of individuals vs. VALE S.A",
	"Brazil NCP_Former distributors vs. Nestle Brasil Ltda",
	"Brazil NCP_CUT vs. Unilever Brasil Alimentos",
	"Brazil NCP_CUT vs. Pertech",
	"Brazil NCP_Contraf and CUT vs. Unibanco",
	"Brazil NCP_CUT vs. C&A Modas",
	"Brazil NCP_CUT vs. BASF S.A",
	"Brazil NCP_CUT vs. ABN AMRO",
	"Brazil NCP_CAVE et al vs. Shell",
	"Brazil NCP_SITICOP and CUT vs. Vale S.A and BHP",
	"Brazil NCP_Both Ends vs. Van Oord, Atradius and Industrial",
	"Brazil NCP_Trade Union vs. Santander",
	"Brazil NCP_Bank Workers Union and CUT vs. Santander",
	"Brazil NCP_Bank Workers Union vs. Itau Unibanco",
	"Brazil NCP_Bank Workers Union vs. Fidelity National BPO",
	"Brazil NCP_Bank Workers Union vs. Banco do Brasil S.A",
	"Brazil NCP_Bank Workers Union vs. Atento",
	"Brazil NCP_Conectas Human Rights vs. Illy Cafe",
	"Brazil NCP_Conectas Human Rights vs. Starbucks",
	"Canada NCP_OT Watch vs. Ivanhoe Mines",
	"Canada NCP_OT Watch vs. Centerra Gold Inc",
	"Canada NCP_NGOs vs. Anvil",
	"Canada NCP_Mining Watch Canada vs. Ascendant Copper",
	"Canada NCP_BMF vs. Sakto Corporations",
	"Canada NCP_Individuals vs. Barrick Gold",
	"Canada NCP_United Tegaru Canada vs. Sun Peak",
	"CanadaNCP_PLOA and ATA vs. Porgera Joint Mine inPapuaNewGuinea",
	"Canada NCP_FENAME vs. Endeavour Mining",
	"Canada NCP_Canada Tibet Commitee vs. ChinaGold",
	"Canada NCP_CIEL vs. GoldCorp",
	"Canada NCP_SEACC vs. Seabridge",
	"Canada NCP_SEACC vs. Imperial Metals",
	"Canada NCP_Justicia y Reparación vs. Yamana Gold",
	"Canada NCP_individuals vs. B2Gold",
	"Canada NCP_Former employees vs. Banro",
	"Canada NCP_Former employees vs. Banro II",
	"Canada NCP_FIDH, CEDHU and Mining Watch vs. Corriente",
	"Canada NCP_Former employees vs. Flemish Investment Limited",
	"Canada NCP_Haycore vs. Klöckner Pentaplast ",
	"Chilean NCP_Individual vs. ICT company",
	"Chilean NCP_UNI vs. Ripley Corp",
	"Chilean NCP_Trade Union vs. Teck & Quebrada Blanca",
	"Chilean NCP_Trade Union vs. Maersk Containers Industry",
	"Chilean NCP_NGOs vs. Marine Harvest Chile",
	"Chilean NCP_Individuals vs. Minera Candelaria",
	"Chilean NCP_Individuals vs. Foreign mining company",
	"Chilean NCP_Individual vs. US based company",
	"Chilean NCP_Escapes Santander vs. Minera Escondida Limitada",
	"Chiliean NCP_Liquidator vs. Tensa",
	"Chilean NCP_CUT vs. Starbucks",
	"Chilean NCP_Arpal vs. Walmart",
	"Chilean NCP_A Complainant vs. A Mining company",
	"Chilean NCP_CUT vs. Unilever",
	"Colombian NCP_Trade Union vs. Drummond Company",
	"Colombian NCP_Trade Union vs. Hoteles Decameron Colombia",
	"Colombian NCP_SINTRAEXXOM vs. ExxonMobil",
	"Colombian NCP_Trade Union vs. Two companies in ICT",
	"Colombian NCP_Individual vs. Company in ICT sector",
	"Colombian NCP_Individual vs, two mining companies",
	"Colombian NCP_Individual vs. Pension and severance fund managem",
	"Czech NCP_Czech Interest Group vs. A company in textile",
	"Danish NCP_Former employees of the Douala vs. A.P Moeller",
	"Danish NCP_ Christian Juhl vs. Bestseller A/S",
	"Danish NCP_Nepenthes vs. DLH",
	"Danish NCP_Individual vs.  a Danish company in Israel",
	"Danish NCP_NCP vs. Ministry of Defence",
	"Danish NCP_Final Agreement ActionAid vs. Arla Food",
	"Danish NCP_Addameer vs. Danish subsidiary of UK",
	"Danish NCP_two NGOs vs. Danish financial institute",
	"Danish NCP_CCC vs. PWT Group",
	"Danish NCP_WVSD vs. Rockwool",
	"Dutch NCP_Notice Hou Friesland Mooi vs. Nuon Energy",
	"Dutch NCP_Aminigboko Community vs. Shell Petroleum Development",
	"Dutch NCP_Amnesty International and FoE vs. Royal Dutch She",
	"Dutch NCP_ATUMA vs. Unilever",
	"Dutch NCP_Bart Stapert vs. Mylan",
	"Dutch NCP_Bralima employees vs. Heineken",
	"Dutch NCP_BWI et al vs. Inter IKEA Holding B.V",
	"Dutch NCP_CCC vs. G-star International BV",
	"Dutch NCP_ENDs et al vs. Atradius Dutch State Business",
	"Dutch NCP_Fenceline Community vs. Pilipinas Shell Petroleum",
	"Dutch NCP_FIVAS et al vs. Bresser",
	"Dutch NCP_FNV Bondgenoten vs. Plaid Netherland",
	"Dutch NCP_FNV et al vs. Chevron",
	"Dutch NCP_FNV vs. Just Eat",
	"Dutch NCP_FoE vs. ING",
	"Dutch NCP_FoE vs. Rabobank",
	"Dutch NCP_FoE vs. Shell Niger Delta",
	"Dutch NCP_Former employees vs. Philips Lighting",
	"Dutch NCP_IUF vs. PvM",
	"Dutch NCP_IUF et al vs. APG Asset Management",
	"Dutch NCP_NIZA vs. CPH",
	"Dutch NCP_Obelle vs. Shell Petroleum Development",
	"Dutch NCP_Oxfam Novi, Green Peace Netherlands et al vs. ING",
	"Dutch NCP_Pobal Chill Chomain vs. Shell Exploration",
	"Dutch NCP_Shehri-CBE vs. Makro-Habib Pakistan",
	"Dutch NCP_SOMO Both Ends vs. ABP/APG",
	"Dutch NCP_SOMO et al vs. Nidera Holding",
	"Dutch NCP_UNI vs. VEON",
	"Dutch NCP_UNI vs. Ikea",
	"Finnish NCP_Association Generation Ferdinand vs. Stora Enso",
	"Finnish NCP_FoE et al vs. Poyry Plc and Xayaburi hydropower",
	"Finnish NCP_Individual vs. Telia Company AB",
	"Finnish NCP_Individuals vs. Nokia",
	"Finnish NCP_individual vs. Kone Oyj",
	"French NCP_Sherpa et al vs. Michelin Group_follow up",
	"French NCP_14 communities vs. COPAGEF, SOMDIAA and SOSUCAM",
	"French NCP_ADBHR vs. Etienne_Alsetex_initial",
	"French NCP_ADHRB vs. Etienne_Alsetex",
	"French NCP_ASF vs. Perenco",
	"French NCP_ASF vs. Perenco_Initial",
	"French NCP_Australian individual vs. French MNE",
	"French NCP_Birlesik Metal vs. DIAM Internatonal",
	"French NCP_CFDT et al vs. Atos Group",
	"French NCP_CGT vs. SODEXO Group",
	"French NCP_ECCHR vs. DEVCOT",
	"French NCP_Force Ouvriere vs. ASPOCOMP OYJ",
	"French NCP_former employees vs. Somadex - Bouygues Construction",
	"French NCP_Friends of Earth vs. EDF Group",
	"French NCP_I Boycott v. Cafe Sirene/Starbucks",
	"French NCP_IMF et al vs. Molex Automotive",
	"French NCP_Individual vs. AES Sonel",
	"French NCP_ITUC vs. VINCI Airport",
	"French NCP_IUF vs. ACCOR",
	"French NCP_IUF vs. Roquette",
	"French NCP_ProDesc vs. EDF",
	"French NCP_SCOP et al vs. UPM",
	"French NCP_Sherpa vs. Bollore_SOCAPALM",
	"French NCP_Sherpa et al vs. Michelin Group",
	"French NCP_trade unions vs. companies in Burma",
	"French NCP_Trade unions vs. Eiffage Energie Group",
	"French NCP_Trade unions vs. Mark Spencer",
	"French NCP_UNI vs. Teleperformance",
	"French NCP_Unite Here vs. NGAM",
	"German NCP_ADIMED vs. Pharmakina",
	"German NCP_Daphne Caruana Galizia Foundation vs. Siemens AG",
	"German NCP_DGB vs. Bayer AG",
	"German NCP_ECCHR vs. Otto Stadtlander",
	"German NCP_ECCHR et al vs. Trovicor",
	"German NCP_ECHHR et al vs. TUV Rheinland",
	"German NCP_German Watch et al vs. Bayer CropScience",
	"German NCP_Germanwatch vs. Volkswagen AG",
	"German NCP_Gesellschaft für bedrohte Völker vs. TÜV SÜD",
	"German NCP_Gesellschaft für bedrohte Völker vs. Volkswagen",
	"German NCP_Greenpeace vs. TotalFinalElf",
	"German NCP_Greenpeace vs. Vattenfall",
	"German NCP_Greenpeace vs. West LB",
	"German NCP_IG Metall vs. Hyundai Motor EU",
	"German NCP_individual vs. Audi AG",
	"German NCP_Individual vs. Bosch Limited",
	"German NCP_Individual vs. NORDEX SE",
	"German NCP_IndustriALL vs. HeidelbergCement AG",
	"German NCP_Metro Habib Employee Union vs. Metro Cash & Carry",
	"German NCP_Society for threatened people vs. TÜV en",
	"German NCP_Suedwind Institut vs. Adidas AG",
	"German NCP_UK NGO vs. German MNE in ICT",
	"German NCP_UK NGO vs. MNE in Luxembourg",
	"German NCP_UNI vs. Deutsche Post and DHL",
	"German NCP_Uwe Kekeritz vs. KiK Textilien",
	"German NCP_Wake up and Fight for Your Rights vs. Neumann Gruppe",
	"Hungarian NCP_A Complainant vs. MNE headquartered in Hungary",
	"Irish NCP_IUF vs. Coca Cola",
	"Irish NCP_CCRT et al vs. Internet Computer Bureau",
	"Irish NCP_SIP vs. Stryker",
	"Irish NCP_SIP vs. Stryker_initial",
	"Irish NCP_IUF vs. Coca Cola/Ballina_initial",
	"Irish NCP_GLAN et al vs. Electricty Supply Board",
	"Irish NCP_Daphne Caruana vs. Accenture PLC",
	"Irish NCP_Individuals vs. Schweppes Holdings_initial",
	"Irish NCP_Individuals vs. Schweppes Holdings",
	"Irish NCP_ Pobal Chill Chomain vs. Shell",
	"Irish NCP_GLAN vs. San Leon Energy",
	"Irish NCP_GLAN vs. CMC Coal Marketing DAC",
	"Italian NCP_Individual vs. ENI S.P.A",
	"Italian NCP_LLF vs. Intesa Sanpaolo",
	"Italian NCP_Individual vs. Italian bank 3",
	"Italian NCP_individual vs. Italian bank 2",
	"Italian NCP_Individual vs. Italian bank",
	"Italian NCP_FIOM-CGIL vs. N.V. BEKAERT",
	"Italian NCP_FIDH et al vs. Italtel",
	"Italian NCP_FIOM-CGIL vs. Ball Beverage Packaging",
	"Italian NCP_Survival vs. Salini",
	"Italian NCP_FIOM-CGIL vs. EATON",
	"Italian NCP_CWA et al vs. ENI and ENI International",
	"Italian NCP_AEFFAA et al vs. RINA Services",
	"Japanese NCP_Japan Cabin Crew Union vs. KLM Royal Dutch Airline",
	"Japanese NCP_TMPCWA vs. Toyota Motor Corporation",
	"Japanese NCP_Local Unions vs. Nestle Japan Ltd",
	"Japanese NCP_Local union vs. Bridgestone",
	"Japanese NCP_Osaka Skynetwork vs. Emirates Japan",
	"Japanese NCP_UAW vs. Renault Nissan Motors",
	"Japanese NCP_Market Force vs. Mizuho_Sumitomo",
	"Japanese NCP_Local Union et al vs. Tower Semiconductor",
	"Japanese NCP_Workers vs. Suzuki Motors",
	"Kazakhtsan NCP_Individual vs. Telia",
	"Kazakhtstan NCP_Individual vs. AiDA Medicus LLP",
	"Kazakstan NCP_Individual vs. Pandora",
	"KNCP_Workers Union vs. Chanel Korea_final",
	"KNCP_Adiy Baimuldinov vs. GM Korea_initial",
	"KNCP_Workers' Union vs. Corning Inc",
	"KNCP_Individual vs. Haagen-Dazs Korea and General Mills Korea",
	"KNCP_KCSSR and KTNC Watch vs. POSCO in Myanmar",
	"KNCP_KTNC Watch vs. Daewoo and KEXIM",
	"KNCP_Korean Metal Workers' Union vs. Hydis Technologies",
	"KNCP_Workers Union vs. Asahi Glass Co",
	"KNCP_Aminigboko Community vs. Daewoo Engineering_initial",
	"KNCP_KTNC Watch vs. Samsung Heavy Industries",
	"KNCP_KTNC Watch, PUSAKA and et al vs. POSCO International",
	"KNCP_KTMC Watch et al vs. KEXIM and SK E&C",
	"Latvian NCP_Norvik Bank vs. Latvia's legal public institutions",
	"Latvian NCP_Individual vs. SIA Omniva_final",
	"Luxembourg NCP_UNI et al vs. Ternium International",
	"Luxembourg NCP_Former workers vs. Pharmakina SA",
	"Luxembourg NCP_FoE Europe et al vs. ArcelorMittal Liberia",
	"New Zealand NCP_Mr and Mrs Y vs. Company Z",
	"New Zealand NCP_Mr and Mrs C vs. Southern Response",
	"New Zealand NCP_Mr and Mrs Y vs. Company X",
	"New Zealand NCP_Mr and Mrs B vs. Company I",
	"Norwegian NCP_Samsung vs. Totalenergies",
	"Norwegian NCP_Fellesforbundet vs. Kongsberg",
	"Norwegian NCP_Society for the Conservation vs. Cermaq ASA",
	"Norwegian NCP_ Agreement between IUF et al and NBIM",
	"Norwegian NCP_IUF vs. NBIM",
	"Norwegian NCP_KTNC watch et al vs. ABP/APG and NBIM",
	"Norwegian NCP_Birlesik Metal vs. NBIM",
	"Norwegian NCP_SOMO vs. Telenor",
	"Norwegian NCP_ Jijnjevaerie Saami village vs. Statkraft",
	"Norwegian NCP_NSCWS vs. Sjøvik AS",
	"Norwegian NCP_Industri Energi vs. DNO ASA",
	"Norwegian NCP_FIVAS vs. Norconsult AS",
	"Norwegian NCP_Joint Statement between FIVAS and Norconsult",
	"Norwegian NCP_FIOH vs. Intex Resources and Mindoro Nickel",
	"Norwegian NCP_CSJA vs. Telenor",
	"Norwegian NCP_Cotton Campaign and Anti-Slavery vs. NBIM",
	"Norwegian NCP_129 Roma v. Norwegian Church Aid",
	"Peru NCP_Oxfam et al vs. DOE RUN PERU and RENCO Group",
	"Peru NCP_Indigenous People vs. Companies in Hotel Industry",
	"Peru NCP_197 Former employees vs. Avianca Holding",
	"Peru NCP_CUT et al  vs. PERUBAR S.A",
	"Peru NCP_Peruvian Workers vs. Telefonica Peru",
	"Polish_NCP_Individual vs. Skawina/Valeo",
	"Polish NCP_Trade Union vs. a foreign MNE",
	"Polish NCP_Frank Bold vs. Grupa OLX",
	"Polish NCP_Individual vs. LOTOS Grupa",
	"Polish NCP_ Development Yes vs. PZU Group",
	"Spanish NCP_UNI vs. Prosegur",
	"Spanish NCP_An individual vs. Iberdrola",
	"Spanish NCP_CSCA vs. a Spanish MNE",
	"Spanish NCP_CSCA vs. a MNE",
	"Spanish NCP_Alliance for Solidarity vs. a Spanish company in Gu",
	"Swedish NCP_Takkom Jerry vs. Nykomb Synergetics",
	"Swedish NCP_Swedwatch vs. Molnlycke",
	"Swedish NCP_Swedwatch vs. Electrolux",
	"Swedish NCP_Jijnjevaerie saami-village vs. Statkraft",
	"Swedish NCP_FoE vs. Atlas Copco and Sandvik",
	"Swedish NCP_CEDHA vs. Nordea",
	"Swedish NCP_Birlesik Metal vs. Systemair AB",
	"Swiss NCP_IUF vs. Bank Lombard Odier Co Ltd",
	"Swiss NCP_Individual vs. World Bank",
	"Swiss NCP_GLAN vs. Glencore",
	"Swiss NCP_Labour Unions vs. Triumph Thailand",
	"Swiss NCP_IUF vs. Nestle Russia",
	"Swiss NCP_IUF vs. Nestle Indonesia",
	"Swiss NCP_Individual vs. Ice Hockey Federation",
	"Swiss NCP_Former employees vs. PharmakinaSA",
	"Swiss NCP_Individual vs. Cerrejon mine",
	"Swiss NCP_STP vs. USB_initial",
	"Swiss NCP Unite Here vs. FIFA",
	"Swiss NCP TuK Indonesia vs. RSPO",
	"Swiss NCP_Tibetan Community vs. IOC",
	"Swiss NCP_Survival International vs. WWF",
	"SwissNCP_STP vs. USB Group",
	"Swiss NCP_STP vs. Credit Suisse",
	"Swiss NCP_STP vs. BKW Group",
	"Swiss NCP_Pesticide Action Network India vs. Syngenta",
	"Swiss NCP_IndustriALL vs. Holcim India and Holcim Group",
	"Swiss NCP_ECCHR vs. Paul Reinhart AG",
	"Swiss NCP_ECHHR vs. Louis Dreyfus Commodities Suisse SA",
	"Swiss_NCP_ELSAM vs. Holcim Indonesia",
	"Swiss NCP_ECCHR vs. Ecom Agroindustrial Corp",
	"Swiss NCP_BWI vs. Lafarge Holcim",
	"Swiss NCP_BWI vs. FIFA",
	"Swiss NCP_ADHRB vs. FIFA",
	"Turkish NCP_Edgeworth vs. Vakifbank",
	"Turkish NCP_LSD vs. TOSYALI",
	"Turkish NCP_Turk Metal Trade Union vs. Putzmeister",
	"UK NCP_ AHN and CBVL vs. Victoria Final Statement",
	"UK NCP_ Group of NGOs vs. Drax gROUP",
	"UK NCP_NGO vs. UK company in security sector",
	"UK NCP_WWF vs. SOCO International",
	"UK NCP_UN Expert Panel vs. Oryx Natural Resources",
	"UK NCP_UN Expert Panel vs. Avient",
	"UK NCP_UN Expert Panel vs. De Beers",
	"UK NCP_NGO vs. UK company",
	"UK NCP_NGO vs. UK Bank II",
	"UK NCP_NGO vs. UK Bank",
	"UK NCP_UK NGO vs. 6 telecommunication companies",
	"UK NCP_The Lead Group vs. Xstrata PLC",
	"UK NCP_Survival International vs. Vedanta",
	"UK NCP_Sakhalin Environment Watch vs. Royal Bank of Scotland",
	"UK NCP_RAID vs. DAS Air",
	"UK NCP_AJTZP, RAID, and PILC vs. Glencore",
	"UK NCP_RAID vs. Anglo American",
	"UK NCP_Malaysian Trade Union vs. BAT",
	"UK NCP_Justica Ambiental vs. BHP Billiton",
	"UK NCP_Individual vs. UK company",
	"UK NCP_GLAN vs. Anglo American",
	"UK NCP_ECCHR vs. Cargill",
	"UK NCP_Corner House vs. BTC Pipeline_followup",
	"UK NCP_Corner house vs. BTC Pipeline",
	"UK NCP_Client Earth vs. BP_initital",
	"UK NCP_CBE vs. National Grid Transco",
	"UK NCP_ADHRB vs. Formula One Group",
	"UK NCP_Global Witness vs. UKEF",
	"UK NCP_ IUF and FLOC vs. BAT",
	"UK NCP_LPHR vs. G4S",
	"UK NCP_RAID vs. ENRC",
	"UK NCP_IAP and WDM vs. GCM",
	"UK NCP_Reprieve vs. BT",
	"UK NCP_Privacy International vs. Gamma International",
	"UK NCP_IUF vs. Compass Group",
	"UK NCP_Crude Accountability vs. KPO Consortium",
	"UK NCP_IUF vs. Unliever",
	"UK NCP_Corner House vs. Bae Systems",
	"UK NCP_ IDI, EC and LICADHO vs. Bonsucro",
	"UK NCP_BIRD vs. HPG",
	"UK NCP_UKLFI vs. PwC",
	"UK NCP_LPHR vs. JCB",
	"US NCP_Individual vs. Gramercy Funds Management LLC",
	"US NCP_Individual vs. CitiBank re DRC",
	"US NCP_Individuals vs. Coca Cola in DRC_II",
	"US NCP_USW et al vs. Crown Holding",
	"US NCP_USW et al vs. ASARCO",
	"US NCP_UFCW vs. Bodega Latina",
	"US NCP_UAW vs. Nissan Motor Co",
	"US NCP_Jamaa vs. US company in Kenya",
	"US NCP_IUF vs. Starwood Hotels and Resorts",
	"US NCP_IUF vs. Pepsi Co",
	"US NCP_IUF vs. Pepsi Co II",
	"USNCP_IUF vs. Mondelez International in Pakistan",
	"US NCP_IUF vs. Coca Cola Amatil",
	"US NCP_IUF vs. Cargill",
	"US NCP_IUF et al vs. McDonalds",
	"US NCP_IndustriALL vs. General Electric",
	"US NCP_Individual vs. US company in Czechoslovakia",
	"US NCP_Greenpeace vs. Herakles Farm",
	"US NCP_FFW vs. Janssen and Johnson&Johnson",
	"US NCP_ECDHR vs. Boeing Company and Lockheed Martin",
	"US NCP_DIP et al vs. Credit Suisse",
	"US NCP_4 individuals vs. Coca Cola",
];
