countries: [];
[
	{ countryName: "Algeria", flag: "🇩🇿" },
	{ countryName: "Argentina", flag: "🇦🇷" },
	{ countryName: "Armenia", flag: "🇦🇲" },
	{ countryName: "Australia", flag: "🇦🇺" },
	{ countryName: "Azerbaijan", flag: "🇦🇿" },
	{ countryName: "Bahrain", flag: "🇧🇭" },
	{ countryName: "Bangladesh", flag: "🇧🇩" },
	{ countryName: "Belarus", flag: "🇧🇾" },
	{ countryName: "Belgium", flag: "🇧🇪" },
	{ countryName: "Benin", flag: "🇧🇯" },
	{ countryName: "Brazil", flag: "🇧🇷" },
	{ countryName: "Burma", flag: "" },
	{ countryName: "Burundi", flag: "🇧🇮" },
	{ countryName: "Cambodia", flag: "🇰🇭" },
	{ countryName: "Cameroon", flag: "🇨🇲" },
	{ countryName: "Canada", flag: "🇨🇦" },
	{ countryName: "Chad", flag: "🇹🇩" },
	{ countryName: "Chagos Island", flag: "" },
	{ countryName: "Chile", flag: "🇨🇱" },
	{ countryName: "China", flag: "🇨🇳" },
	{ countryName: "Colombia", flag: "🇨🇴" },
	{ countryName: "Cote d'Ivoire", flag: "🇨🇮" },
	{ countryName: "Czech Republic", flag: "🇨🇿" },
	{ countryName: "Democratic Republic Of Congo", flag: "🇨🇩" },
	{ countryName: "Denmark", flag: "🇩🇰" },
	{ countryName: "Dominican Republic", flag: "🇩🇴" },
	{ countryName: "Ecuador", flag: "🇪🇨" },
	{ countryName: "Ethiopia", flag: "🇪🇹" },
	{ countryName: "Former Czechoslovakia", flag: "" },
	{ countryName: "France", flag: "🇫🇷" },
	{ countryName: "Gabonese", flag: "🇬🇦" },
	{ countryName: "Georgia", flag: "🇬🇪" },
	{ countryName: "Germany", flag: "🇩🇪" },
	{ countryName: "Ghana", flag: "🇬🇭" },
	{ countryName: "Guatemala", flag: "🇬🇹" },
	{ countryName: "Hungary", flag: "🇭🇺" },
	{ countryName: "India", flag: "🇮🇳" },
	{ countryName: "Indonesia", flag: "🇮🇩" },
	{ countryName: "Iran", flag: "🇮🇷" },
	{ countryName: "Iraq", flag: "🇮🇶" },
	{ countryName: "Ireland", flag: "🇮🇪" },
	{ countryName: "Israel", flag: "🇮🇱" },
	{ countryName: "Italy", flag: "🇮🇹" },
	{ countryName: "Japan", flag: "🇯🇵" },
	{ countryName: "Kazakhstan", flag: "🇰🇿" },
	{ countryName: "Kenya", flag: "🇰🇪" },
	{ countryName: "Korea", flag: "🇰🇷" },
	{ countryName: "Kosovo", flag: "" },
	{ countryName: "Laos", flag: "🇱🇦" },
	{ countryName: "Latvia", flag: "🇱🇻" },
	{ countryName: "Liberia", flag: "🇱🇷" },
	{ countryName: "Luxembourg", flag: "🇱🇺" },
	{ countryName: "Malaysia", flag: "🇲🇾" },
	{ countryName: "Maldives", flag: "🇲🇻" },
	{ countryName: "Mali", flag: "🇲🇱" },
	{ countryName: "Malta", flag: "🇲🇹" },
	{ countryName: "Mexico", flag: "🇲🇽" },
	{ countryName: "Mongolia", flag: "🇲🇳" },
	{ countryName: "Montenegro", flag: "🇲🇪" },
	{ countryName: "Morocco", flag: "🇲🇦" },
	{ countryName: "Mozambique", flag: "🇲🇿" },
	{ countryName: "Myanmar", flag: "🇲🇲" },
	{ countryName: "Nauru", flag: "🇳🇷" },
	{ countryName: "Netherland", flag: "🇳🇱" },
	{ countryName: "New Zealand", flag: "🇳🇿" },
	{ countryName: "Nicaragua", flag: "🇳🇮" },
	{ countryName: "Nigeria", flag: "🇳🇬" },
	{ countryName: "Norway", flag: "🇳🇴" },
	{ countryName: "Occupied Palestinian Territory", flag: "🇵🇸" },
	{ countryName: "Pakistan", flag: "🇵🇰" },
	{ countryName: "Papua New Guinea", flag: "🇵🇬" },
	{ countryName: "Paraguay", flag: "🇵🇾" },
	{ countryName: "Peru", flag: "🇵🇪" },
	{ countryName: "Poland", flag: "🇵🇱" },
	{ countryName: "Portugal", flag: "🇵🇹" },
	{ countryName: "Qatar", flag: "🇶🇦" },
	{ countryName: "Russia", flag: "🇷🇺" },
	{ countryName: "Saudi-Arabia", flag: "🇸🇦" },
	{ countryName: "Senegal", flag: "🇸🇳" },
	{ countryName: "Somalia", flag: "🇸🇴" },
	{ countryName: "South Africa", flag: "🇿🇦" },
	{ countryName: "Spain", flag: "🇪🇸" },
	{ countryName: "Sri Lanka", flag: "🇱🇰" },
	{ countryName: "Sweden", flag: "🇸🇪" },
	{ countryName: "Thailand", flag: "🇹🇭" },
	{ countryName: "The Netherlands", flag: "🇳🇱" },
	{ countryName: "The Philippines", flag: "🇵🇭" },
	{ countryName: "Tibet", flag: "" },
	{ countryName: "Tunisia", flag: "🇹🇳" },
	{ countryName: "Turkey", flag: "🇹🇷" },
	{ countryName: "Turkmenistan", flag: "🇹🇲" },
	{ countryName: "Uganda", flag: "🇺🇬" },
	{ countryName: "Ukraine", flag: "🇺🇦" },
	{ countryName: "Ukraine", flag: "🇺🇦" },
	{ countryName: "United Kingdom", flag: "🇬🇧" },
	{ countryName: "United States", flag: "🇺🇸" },
	{ countryName: "Uruguay", flag: "🇺🇾" },
	{ countryName: "Uzbekistan", flag: "🇺🇿" },
	{ countryName: "Venezuela", flag: "🇻🇪" },
	{ countryName: "Vietnam", flag: "🇻🇳" },
	{ countryName: "Western Sahara", flag: "" },
	{ countryName: "Yemen", flag: "🇾🇪" },
	{ countryName: "Zambia", flag: "🇿🇲" },
];
