//List of filters and subfilters to be used in the entire project.

module.exports.filterCategories = {
	linkedHumanRightsIssue: {
		filterName: "Linked Human Rights/Environmental Issues",
		subfilters: [
			"Adequate Standard of Living",
			"Child/Forced Labour/Modern Slavery",
			"Climate Change/Greenwashing",
			"Collective Bargaining/Union Rights",
			"Consumer Rights",
			"Corruption/Anti-Bribery",
			"Cultural Heritage/Aboriginal Sites",
			"Death/Killings/Serious Injuries",
			"Disclosure",
			"Environmental Harm/Damage",
			"Failure to Address Environmental/Human Rights Risks",
			"Freedom of Expression",
			"Forced Eviction/Land Grabbing/FPIC",
			"Human Rights Abuses during Colonial Times/War",
			"Indigenous/Aboriginal People's Rights",
			"Labour Rights/Workers' Rights",
			"Lack of Stakeholder Consultation",
			"Linked to Conflict/Armed conflict",
			"Migrant Rights",
			"Minority Rights",
			"Privacy Rights",
			"Racism",
			"Right to Safe and Adequate Water",
			"Security Issues",
			"Social Audit",
			"Socio-Economic/Environmental Rights of Local People",
			"Violence/Abuse/Physical Harm",
			"Womens' Rights/Gender Issues",
		],
	},

	hostCountry: {
		filterName: "Host country (Where the violations conducted)",
		subfilters: [
			"🇩🇿 Algeria",
			"🇦🇷 Argentina",
			"🇦🇲 Armenia",
			"🇦🇺 Australia",
			"🇦🇿 Azerbaijan",
			"🇧🇭 Bahrain",
			"🇧🇩 Bangladesh",
			"🇧🇾 Belarus",
			"🇧🇪 Belgium",
			"🇧🇯 Benin",
			"🇧🇷 Brazil",
			"🇲🇲 Burma",
			"🇧🇮 Burundi",
			"🇰🇭 Cambodia",
			"🇨🇲 Cameroon",
			"🇨🇦 Canada",
			"🇹🇩 Chad",
			"🇹🇴 Chagos Island",
			"🇨🇱 Chile",
			"🇨🇳 China",
			"🇨🇴 Colombia",
			"🇨🇮 Cote d'Ivoire",
			"🇨🇿 Czech Republic",
			"🇨🇩 Democratic Republic Of Congo",
			"🇩🇰 Denmark",
			"🇩🇴 Dominican Republic",
			"🇪🇨 Ecuador",
			"🇪🇹 Ethiopia",
			"🇨🇿 Former Czechoslovakia",
			"🇫🇷 France",
			"🇬🇦 Gabonese",
			"🇬🇪 Georgia",
			"🇩🇪 Germany",
			"🇬🇭 Ghana",
			"🇬🇹 Guatemala",
			"🇭🇺 Hungary",
			"🇮🇳 India",
			"🇮🇩 Indonesia",
			"🇮🇷 Iran",
			"🇮🇶 Iraq",
			"🇮🇪 Ireland",
			"🇮🇱 Israel",
			"🇮🇹 Italy",
			"🇯🇵 Japan",
			"🇰🇿 Kazakhstan",
			"🇰🇪 Kenya",
			"🇽🇰 Kosovo",
			"🇱🇦 Laos",
			"🇱🇻 Latvia",
			"🇱🇷 Liberia",
			"🇱🇺 Luxembourg",
			"🇲🇾 Malaysia",
			"🇲🇻 Maldives",
			"🇲🇱 Mali",
			"🇲🇹 Malta",
			"🇲🇽 Mexico",
			"🇲🇳 Mongolia",
			"🇲🇪 Montenegro",
			"🇲🇦 Morocco",
			"🇲🇿 Mozambique",
			"🇲🇲 Myanmar",
			"🇳🇷 Nauru",
			"🇳🇱 Netherlands",
			"🇳🇿 New Zealand",
			"🇳🇮 Nicaragua",
			"🇳🇬 Nigeria",
			"🇳🇴 Norway",
			"🇵🇸 Occupied Palestinian Territory",
			"🇵🇰 Pakistan",
			"🇵🇬 Papua New Guinea",
			"🇵🇾 Paraguay",
			"🇵🇪 Peru",
			"🇵🇭 Philippines",
			"🇵🇱 Poland",
			"🇵🇹 Portugal",
			"🇶🇦 Qatar",
			"🇷🇺 Russia",
			"🇸🇦 Saudi-Arabia",
			"🇸🇳 Senegal",
			"🇸🇴 Somalia",
			"🇿🇦 South Africa",
			"🇰🇷 South Korea",
			"🇪🇸 Spain",
			"🇱🇰 Sri Lanka",
			"🇸🇪 Sweden",
			"🇹🇭 Thailand",
			"🇹🇳 Tunisia",
			"🇹🇷 Turkey",
			"🇹🇲 Turkmenistan",
			"🇺🇬 Uganda",
			"🇺🇦 Ukraine",
			"🇬🇧 United Kingdom",
			"🇺🇸 United States",
			"🇺🇾 Uruguay",
			"🇺🇿 Uzbekistan",
			"🇻🇪 Venezuela",
			"🇻🇳 Vietnam",
			"🇪🇭 Western Sahara",
			"🇾🇪 Yemen",
			"🇿🇲 Zambia",
		],
	},

	corporateInvolvementToTheHarmsAndAbuses: {
		filterName: "Corporate Involvement to Harm/Abuse",
		subfilters: [
			"Caused/Contributed",
			"Directly linked through investment",
			"Linked/Analysis of business relationship in corporate level",
			"Linked/Analysis of business relationship in supply chain",
		],
	},

	// definingRisksHarmsAndAbuse: {
	// 	filterName: "Defining risk/harm/abuses",
	// 	subfilters: [],
	// },

	riskBasedDueDiligenceProcess: {
		filterName: "Risk-based due diligence process under OECD Guidelines",
		subfilters: [
			"Embedding Responsible Business Conduct",
			"Identification/Assessment of Adverse Impacts",
			"Prevention and Mitigation Measures",
			"Leverage/Influence",
			"Cease/Disengagement/Divestment",
			"Monitoring/Tracking the Implementation",
			"Communication about Adverse Impacts",
			"Provide for or Cooperate in Remediation",
		],
	},

	conceptOfHumanRightsDueDiligence: {
		filterName: "Concept of Human Rights Due Diligence",
		subfilters: [
			"Effectiveness of Human Rights Due Diligence",
			"How/when to Conduct Human Rights Due Diligence",
			"Scope under Human Rights Due Diligence",
		],
	},

	stakeholderEngagement: {
		filterName: "Stakeholder Engagement",
		subfilters: [
			"Definition/Identification of Stakeholders",
			"Engagement between Employer and Employees",
			"Effectiveness of Stakeholder Engagement",
		],
	},

	corporateResponsibilitiesForGroups: {
		filterName:
			"Corporate responsibilities for Groups/Human Rights/Environment",
		subfilters: [
			"Responsibilities in Supply Chain",
			"Responsibilities related to Gender Issues",
			"Responsibilities related to Workers' rights",
			"Responsibilities towards Environment/Climate Change",
			"Responsibilities towards Minorities/Indigenous People",
			"Responsibilities in Conflict-Affected Areas",
			"Responsibilities towards Local Development/SDGs",
			"Shared Responsibility/Collective Action",
		],
	},

	responsibilitiesOfDifferentCorporateActors: {
		filterName: "Responsibilities of Different Corporate Actors",
		subfilters: [
			"Audit/Consultancy",
			"Investor/Fiinancial institutions",
			"Non-Profit Organisations",
			"Parent/Group Company",
			"SMEs/Domestic Companies",
			"State-owned Entities",
			"Suppliers",
			"ICT Companies",
		],
	},

	stateResponsibilityInvolvement: {
		filterName: "State responsibility/Involvement",
		subfilters: [
			"State engagement in the NCP proceedings",
			"NCPs' Advises to Government/Authorities to Act",
			"State Guidance to Businesses",
			"State Involvement in the Abuse/Harm",
			"NCPs Reference to State Regulation/View",
		],
	},

	otherSubstantialMatters: {
		filterName: "Other substantial matters",
		subfilters: [
			"Conflict between the Laws/Regulations",
			"Corporate Governance",
			"Mandatory Due Diligence Legislation",
			"NAP on Business and Human Rights",
			"Responsibility under Domestic Laws",
			"Responsibility under the Franchise Contract",
			"SLAPP/Retaliations",
			"Gap in the Guidelines/BHR regulations",
		],
	},

	statusOfTheCase: {
		filterName: "Status of the Case",
		subfilters: [
			"Agreement",
			"Closed (Withdrawal)",
			"Completed without agreement or participation",
			"Rejected (cases with only initial statement)",
		],
	},

	analysisOfContextOfTheNCPStatements: {
		filterName: "Analysis of Context of the NCP Statements",
		subfilters: [
			"Determination of Compliance/Non-compliance",
			"Explanation of OECD Guidelines on Certain Matters",
			"Reference to Previous Similar NCP Statements",
			"Referred International Convention/Treaty/Other Regulation",
			"Referred UN Resolutions/Reports/Documents",
			"Referred ILO Conventions/Recommendations",
			"Referred OECD Guidance Documents",
			"Referred EU and Other Regional Instruments",
			"Referred Mandatory Human Rights Due Diligence Legislation",
			"Referred Multistakeholder Initiatives",
			"Referred Domestic Legislation/Regulation",
			"Referred Other Soft Regulations",
		],
	},

	challengesInNCPProceeding: {
		filterName: "Challenges in NCP Proceeding",
		subfilters: [
			"Difficulty in Verification/Validation of Evidence/Link",
			"Issues with Parallel Proceedings",
			"Delays",
			"Challenges regarding NCP Mandate/Role",
			"Issues with Confidentiality",
			"Challenges for Individual Complainants",
			"Alleged Impartiality of NCPs",
			"Language barriers",
			"Burden of Costs(Travel, translation, Expert Fees)",
		],
	},

	NCPsInvestigationAndMediationApproaches: {
		filterName: "NCPs Investigation and Mediation Approaches",
		subfilters: [
			"Approaches/Penalties for Corporate Non-participation",
			"Effective Cooperation between NCPs",
			"Field Investigation",
			"External Legal Experts/Consultants",
			"Hired Professional Mediators",
			"Translation Service",
			"Inclusion of Victims in the Mediation Process",
			"Independent Research/Fact-finding",
			"NCP Cooperation with Other Organisations",
		],
	},

	outcomeResultOfNCPCase: {
		filterName: "Outcome/Result of the NCP case",
		subfilters: [
			"Agreement Outside the NCP proceeding",
			"Cease of Activity/Disengagement",
			"No Agreement",
			"Acknowledgements/Apologies",
			"Changes of Actions/Policy Made by the Result of NCP Proceedings",
			"Written Agreement Resulted by the NCP proceeding",
			"Financial Compensation/Refund",
		],
	},

	// specificCorporateHumanRightsResponsibilities: {
	// 	filterName:
	// 		"Other specific responsibilities for human rights/environment",
	// 	subfilters: [
	// 		"parent companies managerial responsibility",
	// 		"Responsibility regarding the domestic laws",
	// 		"Responsibility in conflict-affected areas",
	// 		"Responsibility in supply chain",
	// 		"Responsibility towards local development/SDGs",
	// 		"Corporate responsibility towards environmental/climate impact",
	// 		"Collective action/Shared responsibility",
	// 	],
	// },

	// actors: {
	// 	filterName: "Actors - Human rights responsibility",
	// 	subfilters: [
	// 		"Consultant cpmpanies",
	// 		"Audit",
	// 		"SMEs",
	// 		"Non-profit organisations",
	// 		"Tech companies",
	// 		"Parent/Group company",
	// 		"Investor/financial institutions",
	// 		"State responsibility/involvement",
	// 		"Supplier(s)",
	// 	],
	// },

	// otherSubstantialMatters: {
	// 	filterName: "Other substantial matters",
	// 	subfilters: [
	// 		"Conflict between the legislations/regulations",
	// 		"Corporate governance",
	// 		"Gap in the Guidelines/BHR regulations",
	// 		"SLAPP",
	// 	],
	// },

	// NCPsEffortsToResolveTheCases: {
	// 	filterName: "NCPs efforts to resolve the case",
	// 	subfilters: [
	// 		"Hired professional external mediator",
	// 		"Included workers/victims in the mediation process",
	// 		"Independent fact-finding",
	// 		"Hired translators",
	// 		"hired legal expert/consultant",
	// 		"NCP provided advice to government",
	// 		"Approaches/penalties for non-participation",
	// 		"Cooperation between NCPs",
	// 		"Monitored the compliance of companies",
	// 		"NCPs cooperation with other organisations",
	// 	],
	// },

	// NCPGoodOffices: {
	// 	filterName: "Good office types",
	// 	subfilters: [
	// 		"Conciliation approaches",
	// 		"Mediation approaches",
	// 		"Other approaches",
	// 	],
	// },

	// challengesDuringTheGoodOffice: {
	// 	filterName: "Challenges in NCP proceeding",
	// 	subfilters: [
	// 		"Inability of NCPs to determine the link, evidence",
	// 		"No cooperation between the NCPs",
	// 		"Parallel proceedings",
	// 		"Confidentiality",
	// 		"Language barriers",
	// 		"Delays",
	// 	],
	// },

	// outcomesResultOfTheMediation: {
	// 	filterName: "Outcome/result of the NCP mediation",
	// 	subfilters: [
	// 		"No agreement",
	// 		"Acknowledgements/Apologies",
	// 		"Disengagement of the business activities/supplier",
	// 		"Changes of actions/policy made by the result of NCP proceedings",
	// 		"Written agreement resulted by the NCP proceeding",
	// 		"Financial compensation",
	// 		"Monitoring of the actions",
	// 	],
	// },

	// analysisOnStatement: {
	// 	filterName: "Analysis of NCP statement",
	// 	subfilters: [
	// 		"Determination of compliance/non-compliance",
	// 		"Referred instruments in the statement",
	// 		"Refers other NCP decisions",
	// 		"About OECD Guidelines in the NCP statements",
	// 	],
	// },

	// statusOfTheCase: {
	// 	filterName: "Status of the case",
	// 	subfilters: [
	// 		"conclusion without participation",
	// 		"Rejected (apply to cases with only initial statement)",
	// 		"Completed without agreement",
	// 		"Completed (company withdrawn its participation)",
	// 		"Agreement",
	// 	],
	// },
};
