//List of filters and subfilters to be used in the entire project.

module.exports.filterCategories = {
  linkedHumanRightsIssue: {
    filterName: "Linked human rights/issues",
    subfilters: [
      "Racism",
      "Consumer interest",
      "Corruption",
      "Living condition/Inadequate standard of living",
      "Security issues",
      "No stakeholder consultation",
      "Social audit",
      "Child/Forced/Modern slavery",
      "Gender-based violence and harassment",
      "Failed to conduct HRDD/address environmental and social harms",
      "Disclosure",
      "Death/killings",
      "Violence/abuse/physicalharm",
      "Misuse of products/linked to conflict/armed conflict",
      "Environmental harm",
      "Forcible displacement/Land grabbing/FPIC",
      "Collective bargain/Union rights",
      "Indigenous people/Aboriginal people",
      "Cultural heritage/Aboriginal site/",
      "Fossil fuel investment",
      "Distribution of personal data/reputation",
      "Migration and detention of migrants",
      "Climate change/greenwashing",
      "Social and environmental risks to local community",
      "Human rights abuses during the war/Colonial",
      "Labour rights, health risks to employees",
    ],
  },

  hostCountry: {
    filterName: "Host country (Where the violations conducted)",
    subfilters: [
      "🇩🇿 Algeria",
      "🇦🇷 Argentina",
      "🇦🇲 Armenia",
      "🇦🇺 Australia",
      "🇦🇿 Azerbaijan",
      "🇧🇭 Bahrain",
      "🇧🇩 Bangladesh",
      "🇧🇪 Belgium",
      "🇧🇯 Benin",
      "🇧🇷 Brazil",
      "🇲🇲 Burma",
      "🇧🇮 Burundi",
      "🇰🇭 Cambodia",
      "🇨🇲 Cameroon",
      "🇨🇦 Canada",
      "🇹🇩 Chad",
      "🇨🇱 Chile",
      "🇨🇳 China",
      "🇨🇴 Colombia",
      "🇨🇮 Cote d'Ivoire",
      "🇨🇿 Czech Republic",
      "🇨🇿 Former Czechoslovakia",
      "🇨🇩 Democratic Republic Of Congo",
      "🇩🇰 Denmark",
      "🇩🇴 Dominican Republic",
      "🇪🇨 Ecuador",
      "🇪🇹 Ethiopia",
      "🇫🇷 France",
      "🇬🇦 Gabonese",
      "🇬🇪 Georgia",
      "🇩🇪 Germany",
      "🇬🇭 Ghana",
      "🇬🇹 Guatemala",
      "🇭🇺 Hungary",
      "🇮🇳 India",
      "🇮🇩 Indonesia",
      "🇮🇷 Iran",
      "🇮🇶 Iraq",
      "🇮🇪 Ireland",
      "🇮🇱 Israel",
      "🇮🇹 Italy",
      "🇯🇵 Japan",
      "🇰🇿 Kazakhstan",
      "🇰🇪 Kenya",
      "🇰🇷 Korea",
      "🇽🇰 Kosovo",
      "🇱🇦 Laos",
      "🇱🇻 Latvia",
      "🇱🇷 Liberia",
      "🇱🇺 Luxembourg",
      "🇲🇾 Malaysia",
      "🇲🇻 Maldives",
      "🇲🇱 Mali",
      "🇲🇹 Malta",
      "🇲🇽 Mexico",
      "🇲🇪 Montenegro",
      "🇲🇦 Morocco",
      "🇲🇿 Mozambique",
      "🇲🇲 Myanmar",
      "🇳🇷 Nauru",
      "🇳🇱 The Netherlands",
      "🇳🇿 New Zealand",
      "🇳🇮 Nicaragua",
      "🇳🇬 Nigeria",
      "🇳🇴 Norway",
      "🇵🇸 Occupied Palestinian Territory",
      "🇵🇰 Pakistan",
      "🇵🇬 Papua New Guinea",
      "🇵🇾 Paraguay",
      "🇵🇪 Peru",
      "🇵🇭 The Philippines",
      "🇵🇱 Poland",
      "🇵🇹 Portugal",
      "🇶🇦 Qatar",
      "🇷🇺 Russia",
      "🇸🇦 Saudi-Arabia",
      "🇸🇳 Senegal",
      "🇸🇴 Somalia",
      "🇿🇦 South Africa",
      "🇪🇸 Spain",
      "🇱🇰 Sri Lanka",
      "🇸🇪 Sweden",
      "🇹🇭 Thailand",
      "Tibet",
      "🇹🇳 Tunisia",
      "🇹🇷 Turkey",
      "🇹🇲 Turkmenistan",
      "🇺🇬 Uganda",
      "🇺🇦 Ukraine",
      "🇬🇧 United Kingdom",
      "🇺🇸 United States",
      "🇺🇾 Uruguay",
      "🇺🇿 Uzbekistan",
      "🇻🇪 Venezuela",
      "🇻🇳 Vietnam",
      "🇪🇭 Western Sahara",
      "🇾🇪 Yemen",
      "🇿🇲 Zambia",
    ],
  },

  corporateInvolvementToTheHarmsAndAbuses: {
    filterName: "Corporate involvement to harm/abuse",
    subfilters: [
      "Causing/Contributing",
      "Direct/non-direct control",
      "Directly linked",
    ],
  },

  definingRisksHarmsAndAbuse: {
    filterName: "Defining risk/harm/abuses",
    subfilters: [],
  },

  corporateResponsibilityInUNGPsFramework: {
    filterName: "Corporate human rights responsibility in the UNGPs",
    subfilters: [
      "Human rights due diligence",
      "Corporate human rights policy/Code of conduct",
      "Stakeholder engagement",
      "Mitigation/Leverage",
      "Remedy/corporate grievance mechanism",
      "Transparency/communication/disclosure",
    ],
  },

  specificCorporateHumanRightsResponsibilities: {
    filterName: "Other specific responsibilities for human rights/environment",
    subfilters: [
      "parent companies managerial responsibility",
      "Responsibility regarding the domestic laws",
      "Responsibility in conflict-affected areas",
      "Responsibility in supply chain",
      "Responsibility towards local development/SDGs",
      "Corporate responsibility towards environmental/climate impact",
      "Collective action/Shared responsibility",
    ],
  },

  actors: {
    filterName: "Actors - Human rights responsibility",
    subfilters: [
      "Consultant cpmpanies",
      "Audit",
      "SMEs",
      "Non-profit organisations",
      "Tech companies",
      "Parent/Group company",
      "Investor/financial institutions",
      "State responsibility/involvement",
      "Supplier(s)",
    ],
  },

  otherSubstantialMatters: {
    filterName: "Other substantial matters",
    subfilters: [
      "Conflict between the legislations/regulations",
      "Corporate governance",
      "Gap in the Guidelines/BHR regulations",
      "SLAPP",
    ],
  },

  NCPsEffortsToResolveTheCases: {
    filterName: "NCPs efforts to resolve the case",
    subfilters: [
      "Hired professional external mediator",
      "Included workers/victims in the mediation process",
      "Independent fact-finding",
      "Hired translators",
      "hired legal expert/consultant",
      "NCP provided advice to government",
      "Approaches/penalties for non-participation",
      "Cooperation between NCPs",
      "Monitored the compliance of companies",
      "NCPs cooperation with other organisations",
    ],
  },

  NCPGoodOffices: {
    filterName: "Good office types",
    subfilters: [
      "Conciliation approaches",
      "Mediation approaches",
      "Other approaches",
    ],
  },

  challengesDuringTheGoodOffice: {
    filterName: "Challenges in NCP proceeding",
    subfilters: [
      "Inability of NCPs to determine the link, evidence",
      "No cooperation between the NCPs",
      "Parallel proceedings",
      "Confidentiality",
      "Language barriers",
      "Delays",
    ],
  },

  outcomesResultOfTheMediation: {
    filterName: "Outcome/result of the NCP mediation",
    subfilters: [
      "No agreement",
      "Acknowledgements/Apologies",
      "Disengagement of the business activities/supplier",
      "Changes of actions/policy made by the result of NCP proceedings",
      "Written agreement resulted by the NCP proceeding",
      "Financial compensation",
      "Monitoring of the actions",
    ],
  },

  analysisOnStatement: {
    filterName: "Analysis of NCP statement",
    subfilters: [
      "Determination of compliance/non-compliance",
      "Referred instruments in the statement",
      "Refers other NCP decisions",
      "About OECD Guidelines in the NCP statements",
    ],
  },

  statusOfTheCase: {
    filterName: "Status of the case",
    subfilters: [
      "conclusion without participation",
      "Rejected (apply to cases with only initial statement)",
      "Completed without agreement",
      "Completed (company withdrawn its participation)",
      "Agreement",
    ],
  },
};
